schema_version: 1

context:
  python_min: "3.10"
  version: "1.6.0"

package:
  name: e3sm_compareview
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/e/e3sm_compareview/e3sm_compareview-${{ version }}.tar.gz
  sha256: 12f8bdeaf4b77bb08fea2f3394ef5a2231f74d12af0cd3c13f98ec52774b05d8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - compareview = e3sm_compareview.app:main
      - quickcompare = e3sm_compareview.app:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - numpy <2.4
    - e3sm-quickview >=2.7.7

tests:
  - python:
      imports:
        - e3sm_compareview
      pip_check: true
  - requirements:
      run:
        - pip
    script:
      - compareview --help
      - quickcompare --help

about:
  summary: An application to explore/analyze data for atmosphere component for E3SM
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/e3sm-compareview/

extra:
  recipe-maintainers:
    - jourdain
    - willdunklin
